NCCL_P2P_DISABLE=1 OMP_NUM_THREADS=1 CUDA_VISIBLE_DEVICES=0 python -m torch.distributed.launch --nproc_per_node=1 --master_port='29500' main_finetune.py \
    --accum_iter 4 \
    --batch_size 64 \
    --model vit_small_patch16 \
    --finetune /nvme/SpikeZIP_transformer/vit-small-patch16-relu-82.34.pth \
    --resume /nvme/SpikeZIP_transformer/vit-small-patch16-relu-82.34.pth \
    --epochs 100 \
    --blr 5e-4 --layer_decay 0.65 \
    --weight_decay 0.05 --drop_path 0.1 --mixup 0.8 --cutmix 1.0 --reprob 0.25 \
    --dist_eval --data_path /nvme/ImageNet/ --output_dir /home/kang_you/SpikeZIP_transformer/output/ --log_dir /home/kang_you/SpikeZIP_transformer/output/ \
    --mode "ANN" --act_layer relu --wandb --eval --energy_eval