NCCL_P2P_DISABLE=1 OMP_NUM_THREADS=1 CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.run --nproc_per_node=4 --master_port='29500' main_finetune_distill.py \
    --accum_iter 4 \
    --batch_size 32 \
    --model vit_large_patch16 \
    --model_teacher vit_base_patch16 \
    --finetune /nvme/SpikeZIP_transformer/vit-base-imagenet-relu-83.75.pth \
    --pretrain_teacher /nvme/SpikeZIP_transformer/vit-base-imagenet-relu-83.75.pth \
    --epochs 100 \
    --blr 1.5e-4 --layer_decay 0.65 --warmup_epochs 0 \
    --weight_decay 0.05 --drop_path 0.1 --drop_rate 0.0 --mixup 0.8 --cutmix 1.0 --reprob 0.25 \
    --dist_eval --data_path /nvme/ImageNet/ --output_dir /home/kang_you/SpikeZIP_transformer/output --log_dir /home/kang_you/SpikeZIP_transformer/output \
    --mode "QANN_QAT" --level 16 --act_layer relu --act_layer_teacher relu --temp 2.0 --wandb --print_freq 200 --define_params --mean 0.5 0.5 0.5 --std 0.5 0.5 0.5